# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
server:
   port: 5555
   compression:
     enabled: true
   error:
     path: /error
   http2:
     enabled: true
   tomcat:
      max-threads: 20
      basedir: ./target/tomcat
      accesslog:
        enabled: true

# Check all configs in EurekaServerConfigBean.java
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    # Note: In sleuth 3.x it is spring.sleuth.baggage.remote-fields=user_name
    propagation-keys: artId
    traceId128: true
    sampler:
      probability: 1.0 # 0.1 by default (or use Sampler.ALWAYS_SAMPLE)
  cloud:
    config:
      enabled: true

#zuul:
#  prefix: /api
#  routes:
#    articleattributeservice: /articleattribute/**
#    articlenameservice: /articlename/**
#    articlepriceservice: /articleprice/**
#    articleservice: /article/**
