# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
server:
   port: 5555
   compression:
     enabled: true
   error:
     path: /error
   http2:
     enabled: true
   tomcat:
      max-threads: 20
      basedir: ./target/tomcat
      accesslog:
        enabled: true

# Check all configs in EurekaServerConfigBean.java
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

#zuul:
#  prefix: /api
#  routes:
#    articleattributeservice: /articleattribute/**
#    articlenameservice: /articlename/**
#    articlepriceservice: /articleprice/**
#    articleservice: /article/**
        
#Setting logging levels
logging:
    level:
      com.netflix: TRACE
      org.springframework.web: TRACE
      com.sme.springcloud.gateway: TRACE
