apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: spring-microservices-articleprice-service
  name: spring-microservices-articleprice-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: spring-microservices-articleprice-service
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-microservices-articleprice-service
    spec:
      containers:
        -
          image: sme/micro-articleprice-service:0.1
          name: spring-microservices-articleprice-service
          ports:
            -
              containerPort: 8020
              name: http
          env:
            - name: PROFILE
              value: "default"
            - name: SERVER_PORT
              value: "8020"
            - name: CONFIGSERVER_URI
              value: "http://configserver:8888"
            - name: CONFIGSERVER_PORT
              value: "8888"
            - name: DISCOVERYSERVER_URI
              value: "http://discoveryserver:8761/eureka/"
            - name: DISCOVERYSERVER_PORT
              value: "8761"
          volumeMounts:
            - mountPath: /var/log/microservices
              name: log4j    
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "250m"
      restartPolicy: OnFailure
      volumes:
        - name: log4j
          hostPath:
            # directory location on host
            path: /log
            type: Directory
            
          