# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
server:
   port: 8898
   compression:
     enabled: true
   error:
     path: /error
   http2:
     enabled: true
   tomcat:
      max-threads: 20
      basedir: ./target/tomcat
      accesslog:
        enabled: true
spring:
  profiles:
    active: native
  # Check all configuration in spring-cloud-config-server-2.2.3.RELEASE.jar\META-INF\spring-configuration-metadata.json
  cloud:
     config:
       uri: http://localhost:8898
  boot:
    admin:
      client:
        http: http://localhost:8898
        instance:
          metadata: "*"
# A mail notifications about warnings
      notify:
        mail:
          from: "spring.admin.server.noreply@sme.com"
          two: "admin@sme.com"  
  mail:
    host: "smtp.sme.com"
    enabled: true
    
# Admin Server properties
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS        
# Admin Server logging
logging:
  file: admin-boot-application.log 
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
