apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: spring-microservices-discovery-server
  name: spring-microservices-discovery-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: spring-microservices-discovery-server
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-microservices-discovery-server
    spec:
      containers:
        -
          image: sme/micro-discovery-server:0.1
          name: spring-microservices-discovery-server
          ports:
            -
              containerPort: 8761
              name: http
          volumeMounts:
            - mountPath: /var/log/microservices
              name: log4j    
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "250m"
      restartPolicy: OnFailure
      volumes:
        - name: log4j
          hostPath:
            # directory location on host
            path: /log
            type: Directory
      
      