apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: discoveryserver
  name: discoveryserver
  namespace: default
spec:
  selector:
    matchLabels:
      app: discoveryserver
  replicas: 1
  template:
    metadata:
      labels:
        app: discoveryserver
    spec:
      containers:
        -
          image: sme/micro-discovery-server:0.1
          name: discoveryserver
          ports:
            -
              containerPort: 8761
              name: http
          volumeMounts:
            - mountPath: /log/
              name: log4j    
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      #restartPolicy: Always
      volumes:
        - name: log4j
          hostPath:
            # directory location on host
            path: /var/log/microservices
            type: Directory
      
      
