apiVersion: v1
kind: Service
metadata:
  labels:
    app: discoveryserver
  name: discoveryserver
  namespace: default
spec:
  selector:
    app: discoveryserver
  ports:
    - name: http
      port: 8761
      targetPort: 8761
      protocol: TCP
    - name: debug
      port: 5005
      targetPort: 5005
      protocol: TCP
  type: LoadBalancer
