apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-microservices-articleattribute-service
  name: spring-microservices-articleattribute-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: spring-microservices-articleattribute-service
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-microservices-articleattribute-service
    spec:
      containers:
        -
          image: sme/micro-articleattribute-service:0.1
          name: spring-microservices-articleattribute-service
          ports:
            -
              containerPort: 8030
              name: http
          env:
            - name: PROFILE
              value: "default"
            - name: SERVER_PORT
              value: "8030"
            - name: CONFIGSERVER_URI
              value: "http://configserver:8888"
            - name: CONFIGSERVER_PORT
              value: "8888"
            - name: DISCOVERYSERVER_URI
              value: "http://discoveryserver:8761/eureka/"
            - name: DISCOVERYSERVER_PORT
              value: "8761"
          volumeMounts:
            - mountPath: /log/
              name: log4j    
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always
      volumes:
        - name: log4j
          hostPath:
            # directory location on host
            path: /var/log/microservices
            type: Directory
            
          