apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-microservices-articleattribute-service
  name: spring-microservices-articleattribute-service
  namespace: default
spec:
  selector:
    app: spring-microservices-articleattribute-service
  ports:
    - name: http
      port: 8030
      targetPort: http
      protocol: TCP
  type: LoadBalancer
