apiVersion: v1
kind: Service
metadata:
  labels:
    app: configserver
  name: configserver
  namespace: default
spec:
  selector:
    app: configserver
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
  type: LoadBalancer
