apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-microservices-config-server
  name: spring-microservices-config-server
  namespace: default
spec:
  selector:
    app: spring-microservices-config-server
  ports:
    - name: http
      port: 8888
      targetPort: http
      protocol: TCP
  type: LoadBalancer
