apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: configserver
  name: configserver
  namespace: default
spec:
  selector:
    matchLabels:
      app: configserver
  replicas: 1
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        -
          image: sme/micro-config-server:0.1
          name: configserver
          ports:
            -
              containerPort: 8888
              name: http
          env:
            - name: DISCOVERYSERVER_URI
              value: "http://discoveryserver:8761/eureka/"
            - name: DISCOVERYSERVER_PORT
              value: "8761"
          volumeMounts:
            - mountPath: /log/
              name: log4j    
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      #restartPolicy: Never
      volumes:
        - name: log4j
          hostPath:
            # directory location on host
            path: /var/log/microservices
            type: Directory
      
      